### ISSUE TITLE
[BUG] Problème d'affichage

### ISSUE THREAD

**Issue by Alexmdz77** [yungmides/gitESGI-Groupe2#4]
**Bug Description**

**Reproduction Steps**
1. Use ``XYZ`` command with ``ABC`` options.
2. Observe the result.

**Expected Result**

**Attachments**

**Versioning:**
 - OS: [e.g. Ubuntu 18.04]
 - NPM Version [e.g. v6.14.9]
- Module Version [e.g v6.2.0]

**Additional Comments**

**Comment by yungmides** [comment]
Tu n'utilises pas la dernière version de notre programme. Tu dois la mettre à jour, le bug dont tu parles a déjà été corrigé.
